name: uwimana17
channels:
    - bioconda
    - conda-forge
    - https://repo.anaconda.com/pkgs/free/linux-64
    - https://repo.anaconda.com/pkgs/free/noarch
    - https://repo.anaconda.com/pkgs/pro/linux-64
    - https://repo.anaconda.com/pkgs/pro/noarch
    - nodefaults

dependencies:
    - snakemake=5.2.0
    - gawk=4.2.1
    - pyfaidx=0.5.4.1
    - bedtools=2.27.1
    - ucsc-bedgraphtobigwig=332
    - ucsc-bigwigtobedgraph=332

